services:
  postgres:
    image: postgres:15-alpine
    container_name: book_app
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: book_app
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: book_app_rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  postgres_data: